# Generated by Django 4.2.7 on 2023-11-21 04:17

from django.db import migrations, models

def add_unique_constraint(apps, schema_editor):
    Candidatedirectory = apps.get_model('candidate_app', 'Candidatedirectory')
    schema_editor.create_unique(Candidatedirectory._meta.db_table, ['first_name', 'last_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', 'previous_migration_name'),  # Replace with the actual name of the previous migration
    ]

    operations = [
        migrations.RunPython(add_unique_constraint),
    ]